# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkpi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sparkpi.proto',
  package='sparkpi',
  syntax='proto3',
  serialized_pb=_b('\n\rsparkpi.proto\x12\x07sparkpi\"\x15\n\x05Scale\x12\x0c\n\x04size\x18\x01 \x01(\r\"\x13\n\x02Pi\x12\r\n\x05value\x18\x01 \x01(\x01\x32\x31\n\x07SparkPi\x12&\n\x05GetPi\x12\x0e.sparkpi.Scale\x1a\x0b.sparkpi.Pi\"\x00\x62\x06proto3')
)




_SCALE = _descriptor.Descriptor(
  name='Scale',
  full_name='sparkpi.Scale',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='sparkpi.Scale.size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=47,
)


_PI = _descriptor.Descriptor(
  name='Pi',
  full_name='sparkpi.Pi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sparkpi.Pi.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Scale'] = _SCALE
DESCRIPTOR.message_types_by_name['Pi'] = _PI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Scale = _reflection.GeneratedProtocolMessageType('Scale', (_message.Message,), dict(
  DESCRIPTOR = _SCALE,
  __module__ = 'sparkpi_pb2'
  # @@protoc_insertion_point(class_scope:sparkpi.Scale)
  ))
_sym_db.RegisterMessage(Scale)

Pi = _reflection.GeneratedProtocolMessageType('Pi', (_message.Message,), dict(
  DESCRIPTOR = _PI,
  __module__ = 'sparkpi_pb2'
  # @@protoc_insertion_point(class_scope:sparkpi.Pi)
  ))
_sym_db.RegisterMessage(Pi)



_SPARKPI = _descriptor.ServiceDescriptor(
  name='SparkPi',
  full_name='sparkpi.SparkPi',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=70,
  serialized_end=119,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPi',
    full_name='sparkpi.SparkPi.GetPi',
    index=0,
    containing_service=None,
    input_type=_SCALE,
    output_type=_PI,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPARKPI)

DESCRIPTOR.services_by_name['SparkPi'] = _SPARKPI

# @@protoc_insertion_point(module_scope)
